<?php
defined('SYSPATH') OR die('No direct access allowed.');
/**
 * config every sites(use site_id as key)
 *
 * @package
 * @author    FangHao
 * @copyright    © 2010 Cofree Development Group
 */
return array(
        'en'=>array(
            'lang' => array(
                'quick' =>'Quick View',
                'addto' => 'Add to wishlist',	
                'onesize' => 'one size',			
            ),
			'payment'=> array(
				'choosecard' =>'Please choose card type',
				'choosecard1' =>'Please choose your credit card type.',
			),
            'head_footer' => array(
                'head_first'=> 'name',
                'head_second'=>'NEW IN',
                'head_second_first'=>'SHOP BY',
                'head_second_second'=>'This Week',
                'head_second_third'=>'Last Week',
                'head_second_fourth'=>'Last Month',

                'head_third'=>'CLOTHING',
                'head_third_first'=>'SHOP BY CATEGORY',
                'head_third_second'=>'Dresses',
                'head_third_third'=>'Pants&Leggings',
                'head_third_fourth'=>'Jackets',
                'head_third_fifth'=>'Coats',
                'head_third_sixth'=>'Swimwear&Beachwear',
                'head_third_seventh'=>'Plus Size',
                'head_third_eighth'=>'Rompers&Jumpsuits',
                'head_third_ninth'=>'Jeans',
                'head_third_tenth'=>'Tops',
                'head_third_eleventh'=>'Shorts',
                'head_third_tewerth'=>'Skirts',
                'head_third_thirdteen'=>'Sweaters&Knits',
                'head_third_fouteenth'=>'Suits&Co-ords',
                'head_third_fifteenth'=>'View All Clothing',

                'head_fourth'=>'SHOES',
                'head_fourth_first'=>'SHOP BY CATEGORY',
                'head_fourth_second'=>'Flats',
                'head_fourth_third'=>'Sandals',
                'head_fourth_fourth'=>'Platforms',
                'head_fourth_fifth'=>'Lace Up Shoes',
                'head_fourth_sixth'=>'Heels',
                'head_fourth_seventh'=>'Boots',
                'head_fourth_eighth'=>'Sports Shoes',
                'head_fourth_ninth'=>'View All Shoes',

                'head_fifth'=>'ACCESSORIES',
                'head_fifth_first'=>'SHOP BY CATEGORY',
                'head_fifth_second'=>'Bags&Wallets',
                'head_fifth_third'=>'Hats',
                'head_fifth_fourth'=>'Jewelry',
                'head_fifth_fifth'=>'Sunglasses',
                'head_fifth_sixth'=>'Scarves',
                'head_fifth_seventh'=>'Gloves',
                'head_fifth_eighth'=>'Socks&Tights',
                'head_fifth_ninth'=>'Hair Accessories',
                'head_fifth_tenth'=>'Belts',
                'head_fifth_eleventh'=>'Home Decor',
                'head_fifth_tewerth'=>'Beauty',
                'head_fifth_thirdteenth'=>'View All Accessories',

                'head_sixth'=>'THE CHOIES GALAXY',
                'head_sixth_0'=>'Ballerina Sportsluxe',
                'head_sixth_1'=>'Music Festivals',
                'head_sixth_2'=>'Boho Chic',
                'head_sixth_3'=>"90's School Style",
                'head_sixth_4'=>"90's Minimal Style",
                'head_sixth_5'=>'Denim',

                'head_seventh'=>'SALE',
                'head_eighth'=>'WHOLESALE',

                'footer_first'=>'STAY IN THE KNOW',
                'footer_second'=>'SIGN UP',
                'footer_third'=>' CHOIES SOCIAL',
                'footer_fourth'=>'SHIPPING OPTIONS',
                'footer_fifth'=>'RETURNS',
                'footer_sixth'=>'SIZE GUIDE',
                'footer_seventh'=>'MEMBERSHIP',

                'footer_eighth'=>'ABOUT US',
                'footer_eighth_first'=>'Who We Are',
                'footer_eighth_second'=>'Affiliates',
                'footer_eighth_third'=>'Bloggers',
                'footer_eighth_fourth'=>'Copyright Notice',

                'footer_ninth'=>'HELP',
                'footer_ninth_firsh'=>'Contact Us',
                'footer_ninth_second'=>'FAQs',
                'footer_ninth_third'=>'Notice Board',
                'footer_ninth_foutth'=>'How to Order',

                'footer_tenth'=>'SHOPPING GUIDE',
                'footer_tenth_first'=>'Payments',
                'footer_tenth_second'=>'Coupons',
                'footer_tenth_third'=>'Brand List',
                'footer_tenth_fourth'=>'Wholesale',
                'footer_eleventh'=>'WE ACCEPT',
            ),
        ),
        'de'=>array(
            'lang' => array(
                'quick' =>'SCHNELLANSICHT',
                'addto' => 'Zur Wunschliste Hinzufügen',
                'onesize' => 'Eine Größe',
            ),
			'payment'=> array(
				'choosecard' =>'Bitte wählen Sie hier Kartentyp',
				'choosecard1' =>'Bitte wählen Sie Ihren Kreditkartentyp.',
			),
            'head_footer' => array(
                'head_first'=> 'name',
                'head_second'=>'NEUHEITEN',
                'head_second_first'=>'FILTERN NACH',
                'head_second_second'=>'Diese Woche',
                'head_second_third'=>'Letzte Woche',
                'head_second_fourth'=>'Letzter Monat',

                'head_third'=>'BEKLEIDUNG',
                'head_third_first'=>'EINKAUF NACH KATEGORIE',
                'head_third_fifteenth'=>'View All Clothing',

                'head_fourth'=>'SCHUHE',
                'head_fourth_first'=>'EINKAUF NACH KATEGORIE',
                'head_fourth_ninth'=>'View All Shoes',

                'head_fifth'=>'ACCESSOIRES',
                'head_fifth_first'=>'EINKAUF NACH KATEGORIE',
                'head_fifth_thirdteenth'=>'View All Accessories',

                'head_sixth'=>'GALAXIE VON CHOIES',
                'head_seventh'=>'SALE',
                'head_eighth'=>'GROßHANDEL',

                'footer_first'=>'BLEIBEN SIE INFORMIERT',
                'footer_second'=>'ANMELDEN',
                'footer_third'=>'SOZIALE NETZWERKE',
                'footer_fourth'=>'VERSANDARTEN',
                'footer_fifth'=>'RÜCKGABE',
                'footer_sixth'=>'GRÖSSENTABELLE',
                'footer_seventh'=>'MITGLIEDSCHAFT',

                'footer_eighth'=>'ÜBER UNS',
                'footer_eighth_first'=>'Wer wir sind',
                'footer_eighth_second'=>'Partnerprogramm',
                'footer_eighth_third'=>'Bloggers',
                'footer_eighth_fourth'=>'Copyright Notice',

                'footer_ninth'=>'HILFE',
                'footer_ninth_firsh'=>'Kontakt',
                'footer_ninth_second'=>'FAQs',
                'footer_ninth_third'=>'Hinweise',
                'footer_ninth_foutth'=>'Wie man bestellt',

                'footer_tenth'=>'EINKAUFSFÜHRER',
                'footer_tenth_first'=>'Bezahlung',
                'footer_tenth_second'=>'Gutscheine',
                'footer_tenth_third'=>'Brand List',
                'footer_tenth_fourth'=>'Großhandel',
                'footer_eleventh'=>'WIR AKZEPTIEREN',
            ),

        ),
        'es'=>array(
            'lang' => array(
                'quick' =>'VISTA RÁPIDA',
                'addto' => 'AÑADIR A SU LISTA DE DESEOS',
                'onesize' => 'talla única',
            ),
			'payment'=> array(
				'choosecard' =>'Por favor elige el tipo de tarjeta',
				'choosecard1' =>'Por favor elige el tipo de su tarjeta de crédito.',
			),
            'head_footer' => array(
                'head_first'=> 'name',
                'head_second'=>'NEW IN',
                'head_second_first'=>'SHOP BY',
                'head_second_second'=>'This Week',
                'head_second_third'=>'Last Week',
                'head_second_fourth'=>'Last Month',

                'head_third'=>'CLOTHING',
                'head_third_first'=>'SHOP BY CATEGORY',
                'head_third_second'=>'Dresses',
                'head_third_third'=>'Pants&Leggings',
                'head_third_fourth'=>'Jackets',
                'head_third_fifth'=>'Coats',
                'head_third_sixth'=>'Swimwear&Beachwear',
                'head_third_seventh'=>'Plus Size',
                'head_third_eighth'=>'Rompers&Jumpsuits',
                'head_third_ninth'=>'Jeans',
                'head_third_tenth'=>'Tops',
                'head_third_eleventh'=>'Shorts',
                'head_third_tewerth'=>'Skirts',
                'head_third_thirdteen'=>'Sweaters&Knits',
                'head_third_fouteenth'=>'Suits&Co-ords',
                'head_third_fifteenth'=>'View All Clothing',

                'head_fourth'=>'SHOES',
                'head_fourth_first'=>'SHOP BY CATEGORY',
                'head_fourth_second'=>'Flats',
                'head_fourth_third'=>'Sandals',
                'head_fourth_fourth'=>'Platforms',
                'head_fourth_fifth'=>'Lace Up Shoes',
                'head_fourth_sixth'=>'Heels',
                'head_fourth_seventh'=>'Boots',
                'head_fourth_eighth'=>'Sports Shoes',
                'head_fourth_ninth'=>'View All Shoes',

                'head_fifth'=>'ACCESSORIES',
                'head_fifth_first'=>'SHOP BY CATEGORY',
                'head_fifth_second'=>'Bags&Wallets',
                'head_fifth_third'=>'Hats',
                'head_fifth_fourth'=>'Jewelry',
                'head_fifth_fifth'=>'Sunglasses',
                'head_fifth_sixth'=>'Scarves',
                'head_fifth_seventh'=>'Gloves',
                'head_fifth_eighth'=>'Socks&Tights',
                'head_fifth_ninth'=>'Hair Accessories',
                'head_fifth_tenth'=>'Belts',
                'head_fifth_eleventh'=>'Home Decor',
                'head_fifth_tewerth'=>'Beauty',
                'head_fifth_thirdteenth'=>'View All Accessories',

                'head_sixth'=>'THE CHOIES GALAXY',
                'head_sixth_0'=>'Ballerina Sportsluxe',
                'head_sixth_1'=>'Music Festivals',
                'head_sixth_2'=>'Boho Chic',
                'head_sixth_3'=>"90's School Style",
                'head_sixth_4'=>"90's Minimal Style",
                'head_sixth_5'=>'Denim',

                'head_seventh'=>'SALE',
                'head_eighth'=>'WHOLESALE',

                'footer_first'=>'STAY IN THE KNOW',
                'footer_second'=>'SIGN UP',
                'footer_third'=>' CHOIES SOCIAL',
                'footer_fourth'=>'SHIPPING OPTIONS',
                'footer_fifth'=>'RETURNS',
                'footer_sixth'=>'SIZE GUIDE',
                'footer_seventh'=>'MEMBERSHIP',

                'footer_eighth'=>'ABOUT US',
                'footer_eighth_first'=>'Who We Are',
                'footer_eighth_second'=>'Affiliates',
                'footer_eighth_third'=>'Bloggers',
                'footer_eighth_fourth'=>'Copyright Notice',

                'footer_ninth'=>'HELP',
                'footer_ninth_firsh'=>'Contact Us',
                'footer_ninth_second'=>'FAQs',
                'footer_ninth_third'=>'Notice Board',
                'footer_ninth_foutth'=>'How to Order',

                'footer_tenth'=>'SHOPPING GUIDE',
                'footer_tenth_first'=>'Payments',
                'footer_tenth_second'=>'Coupons',
                'footer_tenth_third'=>'Brand List',
                'footer_tenth_fourth'=>'Wholesale',
                'footer_eleventh'=>'WE ACCEPT',
            ),

        ),
        'fr'=>array(
            'lang' => array(
                'quick' =>'VUE RAPIDE',
                'addto' => "Ajouter à la liste d'envies",
                'onesize' => 'taille unique',
            ),
			'payment'=> array(
				'choosecard' =>'Veuillez choisir le type de carte',
				'choosecard1' =>'Veuillez choisir le type de carte de crédit.',
			),
            'head_footer' => array(
                'head_first'=> 'name',
                'head_second'=>'NOUVEAU',
                'head_second_first'=>'PRODUITS PAR',
                'head_second_second'=>'Cette semaine',
                'head_second_third'=>'La semaine dernière',
                'head_second_fourth'=>'Le mois dernier',
                'head_second_fifth'=>'Prévente',


                'head_third'=>'VÊTEMENTS',
                'head_third_first'=>'PRODUITS PAR CATÉGORIE',
                'head_third_0'=>'Tous les vêtements',
                'head_third_1'=>'Robes',
                'head_third_2'=>'Pantalons & Leggings',
                'head_third_3'=>'Blousons',
                'head_third_4'=>'Manteaux',
                'head_third_5'=>'Maillots de bain',
                'head_third_6'=>'Grande Taille',
                'head_third_7'=>'Combinaisons',
                'head_third_8'=>'Jeans',
                'head_third_9'=>'Tops',
                'head_third_10'=>'Shorts',
                'head_third_11'=>'Jupes',
                'head_third_12'=>'Pulls & Tricots',
                'head_third_13'=>'Ensemble',


                'head_fourth'=>'CHAUSSURES',
                'head_fourth_first'=>'PRODUITS PAR CATÉGORIE',
                'head_fourth_0'=>'Toutes les chaussures',
                'head_fourth_1'=>'Chaussure plates',
                'head_fourth_2'=>'Sandales',
                'head_fourth_3'=>'Platformes',
                'head_fourth_4'=>'Chaussures à lacets',
                'head_fourth_5'=>'Talons',
                'head_fourth_6'=>'Bottes',
                'head_fourth_7'=>'Chaussures de sport',

                'head_fifth'=>'ACCESSORIES',
                'head_fifth_first'=>'PRODUITS PAR CATÉGORIE',
                'head_fifth_0'=>'Tous les accessoires',
                'head_fifth_1'=>'Sacs & Portefeuilles',
                'head_fifth_2'=>'Chapeaux',
                'head_fifth_3'=>'Bijoux',
                'head_fifth_4'=>'Lunettes de soleil',
                'head_fifth_5'=>'Echarpes',
                'head_fifth_6'=>'Gants',
                'head_fifth_7'=>'Chaussettes & Collants',
                'head_fifth_8'=>'Accessoires pour cheveux',
                'head_fifth_9'=>'Ceintures',
                'head_fifth_10'=>'Décoration intérieure',
                'head_fifth_11'=>'Beauté',

                'head_sixth'=>'LA GALAXIE DE CHOIES',
                'head_sixth_0'=>'Ballerine sport de luxe',
                'head_sixth_1'=>'Festival de musique',
                'head_sixth_2'=>'Bohème chic',
                'head_sixth_3'=>"Style de campus des années 90",
                'head_sixth_4'=>"Style minimal des années 90",
                'head_sixth_5'=>'Jean',

                'head_seventh'=>'Vente',
                // 'head_eighth'=>'WHOLESALE',

                'footer_first'=>'RESTER DANS-LE-SAVOIR',
                'footer_second'=>"S'INSCRIRE",
                'footer_third'=>'RÉSEAU SOCIAL',
                'footer_fourth'=>"OPTIONS D'EXPÉDITION",
                'footer_fifth'=>'RETOURS',
                'footer_sixth'=>'GUIDE DES TAILLES',
                'footer_seventh'=>'ADHÉSION',

                'footer_eighth'=>'À PROPOS DE NOUS',
                'footer_eighth_first'=>'Qui nous sommes',
                'footer_eighth_second'=>'Filiales',
                'footer_eighth_third'=>'Bloggers',
                'footer_eighth_fourth'=>'Avis de Copyright',

                'footer_ninth'=>'AIDE',
                'footer_ninth_firsh'=>'Contactez-Nous',
                'footer_ninth_second'=>'FAQs',
                'footer_ninth_third'=>"Tableau d'affichage",
                'footer_ninth_foutth'=>'Comment commander',

                'footer_tenth'=>"GUIDE D'ACHAT",
                'footer_tenth_first'=>'Paiements',
                'footer_tenth_second'=>'Coupons',
                'footer_tenth_third'=>'Liste de Marque',
                'footer_tenth_fourth'=>'Vente en gros',
                'footer_eleventh'=>'Nous acceptons',
            ),

        ),
        'ru'=>array(
            'lang' => array(
                'quick' =>'Бстрый посмотр',
                'addto' => 'Добавить в избранное',
                'onesize' => 'только один размер',
            ),
			'payment'=> array(
				'choosecard' =>'Пожалуйста, выберите тип карты',
				'choosecard1' =>'Пожалуйста, выберите тип кредитной карты.',
			),

        ),
        
);

